features:
- StateID
- DistrictID
- IHHLTotal
- IHHLTotalAch
- CoverageGap
- AchievementRate
hybrid_model: Sequential CSA + ALOA
project: Sanitation Infrastructure Completion Prediction
target: IHHLCoveragePer
