features:
- StateID
- DistrictID
- IHHLTotal
- IHHLTotalAch
- CoverageGap
- AchievementRate
hybrid_model: PSO + CSA
project: Sanitation Infrastructure Completion Prediction
target: IHHLCoveragePer
