features:
- StateID
- DistrictID
- IHHLTotal
- IHHLTotalAch
- CoverageGap
- AchievementRate
hybrid_model: Sequential ALOA + WOA
project: Sanitation Infrastructure Completion Prediction
target: IHHLCoveragePer
